### ISSUE TITLE
Cleanup old issues

### ISSUE THREAD

**Issue by Epictek** [termux/termux-api#208]
I'm wanting to help implement some of the backlogs of feature requests but there is a bit of a clutter of old issues that probably need closing, thought I'd make someone's job easier and list all the ones that should probably be closed.

- [x] https://github.com/termux/termux-api/issues/17 Accessible via `termux-sensor -s GYROSCOPE`
- [x] https://github.com/termux/termux-api/issues/111 https://github.com/termux/termux-api/issues/42 https://github.com/termux/termux-api/issues/23 https://github.com/termux/termux-api/issues/77 Fixed in https://github.com/termux/termux-api/pull/172
- [x] https://github.com/termux/termux-api/issues/74 implemented in https://github.com/termux/termux-api/pull/158
- [x] https://github.com/termux/termux-api/issues/99 Is now implemented via `termux-wifi-connectioninfo`, `termux-wifi-enable` & `termux-wifi-scaninfo`
- [x] https://github.com/termux/termux-api/issues/131 implemented in https://github.com/termux/termux-api/pull/170
- [x] https://github.com/termux/termux-api/issues/117 Implemented in https://github.com/termux/termux-api/pull/147
- [ ] https://github.com/termux/termux-api/issues/85 not relevant to termux-api?
- [ ] https://github.com/termux/termux-api/issues/151 not an issue?

**Comment by Grimler91** [comment]
Big thanks!
